name: Install & configure monitoring tool

on: [push]
env:
    CLUSTER_NAME: dockercoins-cluster-teo
    CLUSTER_ZONE: europe-west1-b
    PROJECT_NAME: teolia-school-devops

      
jobs:
  InstallAndConfigureMonitoring:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@master

      - name: Authenticate to GKE
        uses: "./.github/template/authenticate" #Just need to pass the path from action
       # Defining the variables required in our action
        with:
          gcloud_key: ${{ secrets.GCLOUD_KEY }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          cluster_zone: ${{ env.CLUSTER_ZONE }}
          project_name: ${{ env.PROJECT_NAME }}